FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci
CMD ["npx", "prisma", "db", "push", "--accept-data-loss"]
